In [2]:
#import numpy
import numpy as np

In [3]:
my_list=[1,2,3,4,5]

In [4]:
arr1=np.array(my_list)

In [5]:
print(arr1)

[1 2 3 4 5]


In [6]:
type(arr1)

numpy.ndarray

In [27]:
#multi-nested array
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]

In [28]:
arr1=np.array([my_list1,my_list2,my_list3])

In [30]:
print(arr1)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [31]:
type(arr1)

numpy.ndarray

In [119]:
arr1.shape

(3, 5)

In [ ]:
# indexing

In [33]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [34]:
arr2=np.array(my_list1)

In [51]:
arr2

array([1, 2, 3, 4, 5])

In [52]:
# [1:,:2] means include all rows start from 1 and all 
# columns excluding 2

In [36]:
arr1[1:,:2]

array([[2, 3],
       [9, 7]])

In [37]:
# 0:2 means row 2 is not included

In [41]:
arr1[1:,3:]

array([[5, 6],
       [8, 9]])

In [53]:
arr1[1:2,1:4]

array([[3, 4, 5]])

In [54]:
arr2=np.arange(0,10)

In [56]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr2=np.arange(1,10,3)

In [59]:
arr2

array([1, 4, 7])

In [ ]:
#linspace gives same space for all

In [60]:
np.linspace(1,10,8)

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [ ]:
#here the gap is 0.18367347

In [61]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [64]:
arr2

array([1, 4, 7])

In [65]:
arr3=np.array([1,2,3,4,5,6,7,8,9])

In [66]:
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
type(arr3)

numpy.ndarray

In [2]:
#copy function and broadcasting

In [ ]:
# from index 3, make all 100 (included index 3)

In [68]:
arr3[3:]=100

In [69]:
arr3

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [70]:
arr4=arr3

In [71]:
arr4[3:]=500

In [73]:
arr4

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [ ]:
#array is reference type,also change arr3.
# in order to prevent this use  arr.copy() 

In [74]:
arr3

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [75]:
arr5=arr3.copy()

In [77]:
arr5[3:]=1000

In [78]:
arr5

array([   1,    2,    3, 1000, 1000, 1000, 1000, 1000, 1000])

In [79]:
arr3

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [82]:
#some conditions very useful in exploratory data analysis:

In [83]:
arr5<2

array([ True, False, False, False, False, False, False, False, False])

In [84]:
arr5*2

array([   2,    4,    6, 2000, 2000, 2000, 2000, 2000, 2000])

In [85]:
#if you want elements which are less than 1000

In [87]:
arr5[arr5<6]

array([1, 2, 3])

In [88]:
arr5

array([   1,    2,    3, 1000, 1000, 1000, 1000, 1000, 1000])

In [89]:
#create arrays and reshape

In [90]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# multiplying two arrays internally

In [92]:
arr4*arr5

array([     1,      4,      9, 500000, 500000, 500000, 500000, 500000,
       500000])

In [ ]:
# default data-type is float, that's why 1 has dot+
# attached to it. (press shft+tab)

In [93]:
np.ones(4)

array([1., 1., 1., 1.])

In [94]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [ ]:
#multi-dimension array

In [95]:
np.ones((2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [99]:
#random distribution

In [ ]:
#random.rand() gives random numbers b/w 0 and 1.

In [102]:
np.random.rand(3,3)

array([[0.0204996 , 0.8037483 , 0.60865037],
       [0.04229544, 0.42834846, 0.92954689],
       [0.90517767, 0.67208309, 0.34431477]])

In [ ]:
# Return a sample (or samples) from the "standard normal"
# distribution.


In [100]:
arr_ex=np.random.randn(4,4)

In [101]:
arr_ex

array([[-0.52104349, -1.07339386, -1.14447913, -2.38492926],
       [-0.31167863, -0.74921944,  0.6966245 ,  0.80376457],
       [ 0.08147141, -0.60420128, -0.557654  ,  0.57624708],
       [ 0.29417689,  0.6478138 ,  0.6434995 , -0.02225303]])

In [106]:
import pandas as pd

In [ ]:
# between 0 and 100, select 8 int values

In [110]:
arr8 = np.random.randint(0,100,8)

In [ ]:
# randint giving duplicate values 

In [108]:
np.random.randint(10,14,6)

array([12, 10, 10, 13, 12, 12])

In [112]:
arr8

array([80, 28, 50, 85, 56,  3, 81, 54])

In [ ]:
# arr8  contains 8 elements so we can reshape it in 4*2

In [117]:
arr8.reshape(4,2)

array([[80, 28],
       [50, 85],
       [56,  3],
       [81, 54]])

In [ ]:
# Results are from the "continuous uniform" distribution

In [ ]:
# random_sample takes only 1 argument

In [115]:
np.random.random_sample((1,5))

array([[0.91010196, 0.90306028, 0.23354007, 0.50080271, 0.96226096]])

In [122]:
np.random.random_sample((1,8))

array([[0.6767979 , 0.00181512, 0.70540863, 0.72891488, 0.82349604,
        0.39304965, 0.75761792, 0.41661972]])

In [ ]:
# why so many values?

In [121]:
np.random.random_sample((4,9))

array([[0.18485879, 0.81972638, 0.63759892, 0.83306311, 0.05529604,
        0.01892266, 0.78882565, 0.74329559, 0.43949248],
       [0.83172243, 0.81308596, 0.49737153, 0.62905805, 0.27834699,
        0.74585674, 0.4412163 , 0.13703012, 0.84881077],
       [0.00792821, 0.60332481, 0.32169162, 0.56607308, 0.9025585 ,
        0.73367494, 0.88729999, 0.00931017, 0.3794951 ],
       [0.01648258, 0.99559318, 0.80752771, 0.01791717, 0.87493147,
        0.12363347, 0.8568405 , 0.72929625, 0.01806734]])